apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentiment-service
  description: Service that analyzes sentiment from guestbook entries
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: minikube-lab