name: Build and Push Docker Image(s)

on:
  push:
    paths:
      - 'flask-guestbook/app/**'
      - 'sentiment-service/app/**'
      - '.github/workflows/docker-publish.yml'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      # --- Flask Guestbook ---
      - name: Build and push flask-guestbook image
        uses: docker/build-push-action@v5
        with:
          context: ./flask-guestbook/app
          file: ./flask-guestbook/app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/flask-guestbook:latest
            ghcr.io/${{ github.repository_owner }}/flask-guestbook:${{ github.sha }}

      # --- Sentiment Service (Go) ---
      - name: Build and push sentiment-service image
        uses: docker/build-push-action@v5
        with:
          context: ./sentiment-service/app
          file: ./sentiment-service/app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/sentiment-service:latest
            ghcr.io/${{ github.repository_owner }}/sentiment-service:${{ github.sha }}